version: '3.1'

services:
  bookmanagerdb:
    image: mongo

  bookmanager.api:
    image: ${DOCKER_REGISTRY-}bookmanagerapi
    build:
      context: .
      dockerfile: src/Services/BookManager/BookManager.API/Dockerfile
  
  basketmanagerdb:
    image: redis

  basketmanager.api:
    image: ${DOCKER_REGISTRY-}basketmanagerapi
    build:
      context: .
      dockerfile: src/Services/BasketManager/BasketManager.API/Dockerfile
 
  reservationdb:
    image: postgres
  
  reservationmanager.api:
    image: ${DOCKER_REGISTRY-}reservationmanagerapi
    build:
      context: .
      dockerfile: src/Services/ReservationManager/Dockerfile

volumes:
  mongo_data:
  redis_data:
  postgres_data: