version: '3.4'

services:

  bookmanagerdb:
    container_name: bookmanagerdb
    restart: always
    ports:
        - "27018:27017"
    volumes:
        - mongo_data:/data/db

  bookmanager.api:
    container_name: bookmanager.api
    depends_on:
      - bookmanagerdb
    ports:
      - "8091:80"

  basketmanagerdb:
    container_name: basketmanagerredis
    restart: always
    ports:
        - "6380:6379"
    volumes:
        - redis_data:/data/redis

  basketmanager.api:
    container_name: basketmanager.api
    depends_on:
      - basketmanagerdb
    ports:
      - "8092:80"

  
  reservationdb:
    container_name: reservationpostgres
    restart: always
    environment:
      - POSTGRES_USER=orkunuysal
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ReservationDB
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
       - "6390:5432"
    volumes:
       - "postgres_data:/data/postgres"
       - .:/docker-entrypoint-initdb.d

  reservationmanager.api:
    container_name: reservationmanager.api
    depends_on:
      - reservationdb
    ports:
      - "8093:80"
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"