version: '3.1'

services:
  bookmanagerdb:
    image: mongo

  bookmanager.api:
    image: ${DOCKER_REGISTRY-}bookmanagerapi
    build:
      context: .
      dockerfile: src/Services/BookManager/BookManager.API/Dockerfile
  
  basketmanagerdb:
    image: redis

  basketmanager.api:
    image: ${DOCKER_REGISTRY-}basketmanagerapi
    build:
      context: .
      dockerfile: src/Services/BasketManager/BasketManager.API/Dockerfile
    

volumes:
  mongo_data:
  redis_data: