version: '3.4'

services:

  bookmanagerdb:
    container_name: bookmanagerdb
    restart: always
    ports:
        - "27018:27017"
    volumes:
        - mongo_data:/data/db

  bookmanager.api:
    container_name: bookmanager.api
    depends_on:
      - bookmanagerdb
    ports:
      - "8091:80"