version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3.9.8-management-alpine

  bookmanagerdb:
    image: mongo

  reservationdb:
    image: postgres
  
  basketmanagerdb:
    image: redis

  bookmanager.api:
    image: ${DOCKER_REGISTRY-}bookmanagerapi
    build:
      context: .
      dockerfile: src/Services/BookManager/BookManager.API/Dockerfile
  
  basketmanager.api:
    image: ${DOCKER_REGISTRY-}basketmanagerapi
    build:
      context: .
      dockerfile: src/Services/BasketManager/BasketManager.API/Dockerfile
 
  reservationmanager.api:
    image: ${DOCKER_REGISTRY-}reservationmanagerapi
    build:
      context: .
      dockerfile: src/Services/ReservationManager/Dockerfile

  libraryapigateway:
    image: ${DOCKER_REGISTRY-}libraryapigateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1

volumes:
  mongo_data:
  redis_data:
  postgres_data:
  elastic_data:


networks:
  librarynetwork:
    driver: bridge
  elastic:
    driver: bridge