version: '3.4'

services:

  bookmanagerdb:
    container_name: bookmanagerdb
    restart: always
    ports:
        - "27018:27017"
    volumes:
        - mongo_data:/data/db

  bookmanager.api:
    container_name: bookmanager.api
    depends_on:
      - bookmanagerdb
    ports:
      - "8091:80"

  basketmanagerdb:
    container_name: basketmanagerredis
    restart: always
    ports:
        - "6380:6379"
    volumes:
        - redis_data:/data/redis

  basketmanager.api:
    container_name: basketmanager.api
    depends_on:
      - basketmanagerdb
    ports:
      - "8092:80"